version: '3.7'

services:
  postgresql:
    container_name: postgre_db
    image: postgres:15.2-alpine3.17
    env_file:
      - .env
    volumes:
      - /opt/docker/postgres/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

  postgresql_test:
    container_name: postgre_db_test
    image: postgres:15.2-alpine3.17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_TEST}
    ports:
      - "6000:5432"
    restart: always
    networks:
      - custom

  redis:
    container_name: redis
    image: redis:latest
    depends_on:
      - postgresql
    env_file:
      - .env
    volumes:
      - /opt/docker/redis/etc:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - "6379:6379"
    restart: always
    networks:
      - custom

  app:
    container_name: app
    command: ["bash", "../scripts/app.sh"]
    image: app
    depends_on:
      - postgresql
      - postgresql_test
      - redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: always
    networks:
      - custom

  celery:
    container_name: celery
    command: ["bash", "../scripts/celery.sh", "celery"]
    image: app
    depends_on:
      - app
      - redis
    build:
      context: .
    restart: always
    networks:
      - custom

  flower:
    container_name: flower
    command: ["bash", "../scripts/celery.sh", "flower"]
    image: app
    depends_on:
      - app
      - redis
      - celery
    build:
      context: .
    ports:
      - "5555:5555"
    restart: always
    networks:
      - custom

networks:
  custom:
    driver: bridge
