"""add domain_data table

Revision ID: f1ef3905ea85
Revises: 46a68a17fe19
Create Date: 2023-07-23 15:58:50.506471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ef3905ea85'
down_revision = '46a68a17fe19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_data',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('main_info', sa.JSON(), nullable=False),
    sa.Column('active_users', sa.JSON(), nullable=False),
    sa.Column('incoming_line', sa.JSON(), nullable=False),
    sa.Column('user_info', sa.JSON(), nullable=False),
    sa.Column('contacts_user', sa.JSON(), nullable=False),
    sa.Column('groups_user', sa.JSON(), nullable=False),
    sa.Column('group_info', sa.JSON(), nullable=False),
    sa.Column('users_in_group', sa.JSON(), nullable=False),
    sa.Column('names_id_ivr', sa.JSON(), nullable=False),
    sa.Column('ivr_params_events', sa.JSON(), nullable=False),
    sa.Column('route_info', sa.JSON(), nullable=False),
    sa.Column('route_settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('domain_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_data')
    # ### end Alembic commands ###
